Repository Draegerwerk/sdc11073, pull requests merged in 2023-08, with the labels that each got.

#226 fixed matching_services method, add typing to location.py
  CHANGELOG.md
  src/sdc11073/location.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/provider/sco.py
  src/sdc11073/provider/scopesfactory.py
  src/sdc11073/wsdiscovery/wsdimpl.py
  tests/test_sdclocation.py
  tests/test_statecontainers.py
Labels: bug, v2

#227 222 feature use pytest xdist to optimize execution of unittests
  .github/workflows/build.yml
  pyproject.toml
  tests/test_alertsignaldelegate.py
  tests/test_client_device.py
  tests/test_compression.py
  tests/test_device.py
  tests/test_device_periodic_reports.py
  tests/test_device_services.py
  tests/test_discovery.py
  tests/test_operations.py
  tests/test_string_enum_descriptors.py
  tests/test_tutorial.py
  tests/utils.py
Labels: enhancement, v2

#229 Adapt the changelog for the release 1.2.0
  CHANGELOG.md
Labels: v1

#230 make unittest parallelize
  .github/workflows/build.yml
  pyproject.toml
  tests/base_test.py
  tests/test_alertsignaldelegate.py
  tests/test_client_device.py
  tests/test_compression.py
  tests/test_device.py
  tests/test_device_services.py
  tests/test_discovery.py
  tests/test_tutorial.py
  tests/utils.py
Labels: enhancement, v1

#237 228 get adapter containing ip can fail if target address is in a different subnet
  CHANGELOG.md
  src/sdc11073/consumer/consumerimpl.py
Labels: bug, v2

#234 Fix/binding mdib version
  CHANGELOG.md
  src/sdc11073/mdib/devicemdib.py
  src/sdc11073/roles/contextprovider.py
  tests/test_client_device.py
  tutorial/provider/provider.py
Labels: bug, v1

#236 Feature/no reconnect
  CHANGELOG.md
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/httpserver/httprequesthandler.py
  src/sdc11073/httpserver/httpserverimpl.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/pysoap/soapclient.py
  src/sdc11073/pysoap/soapclient_async.py
  tests/mockstuff.py
  tests/test_client_device.py
  tests/test_soapclient.py
Labels: enhancement, v2

#240 fix implicit export of modules in __init__
  src/sdc11073/__init__.py
  src/sdc11073/consumer/__init__.py
  src/sdc11073/mdib/__init__.py
  src/sdc11073/observableproperties/__init__.py
  src/sdc11073/provider/__init__.py
  src/sdc11073/pysoap/__init__.py
  src/sdc11073/roles/__init__.py
Labels: enhancement, v2

#239 238 ext extension containerpropertiesextensionnodeproperty comparison is not as expected
  .github/workflows/publish.yml
  CHANGELOG.md
  pyproject.toml
  src/sdc11073/xml_types/xml_structure.py
  tests/test_pmtypes.py
Labels: bug, v2

#233 232 bug copy node assumes namespaces are constant
  CHANGELOG.md
  src/sdc11073/mdib/clientmdib.py
  src/sdc11073/xmlparsing.py
  tests/test_mdib.py
  tests/test_xmlparsing.py
Labels: bug, v1

#216 Add ssl context container
  .github/workflows/mypy.yml
  .github/workflows/ruff.yml
  .gitignore
  CHANGELOG.md
  examples/ReferenceTest/reference_consumer.py
  examples/ReferenceTest/reference_provider.py
  examples/ReferenceTest/test_reference.py
  src/sdc11073/certloader.py
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/httpserver/httpserverimpl.py
  src/sdc11073/provider/providerimpl.py
  tests/mockstuff.py
  tests/test_alertsignaldelegate.py
  tests/test_client_device.py
  tests/test_client_waveform.py
  tests/test_compression.py
  tests/test_device_periodic_reports.py
  tests/test_operations.py
  tests/test_string_enum_descriptors.py
  tests/test_tutorial.py
Labels: enhancement, v2

#246 Fix/extension local value list
  CHANGELOG.md
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/providermdib.py
  src/sdc11073/mdib/providermdibxtra.py
  src/sdc11073/xml_types/xml_structure.py
  tests/test_client_device.py
  tests/test_descriptorcontainers.py
  tests/test_device_periodic_reports.py
  tests/test_pmtypes.py
Labels: bug, v2
