Repository Draegerwerk/sdc11073, pull requests merged in 2023-10, with the labels that each got.

#266 Fix/operation invoked report
  CHANGELOG.md
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/consumer/operations.py
  src/sdc11073/loghelper.py
  src/sdc11073/mdib/consumermdibxtra.py
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/provider/dpwshostedservice.py
  src/sdc11073/provider/operations.py
  src/sdc11073/provider/porttypes/contextserviceimpl.py
  src/sdc11073/provider/porttypes/descriptioneventserviceimpl.py
  src/sdc11073/provider/porttypes/porttypebase.py
  src/sdc11073/provider/porttypes/setserviceimpl.py
  src/sdc11073/provider/porttypes/stateeventserviceimpl.py
  src/sdc11073/provider/porttypes/waveformserviceimpl.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/provider/sco.py
  src/sdc11073/provider/subscriptionmgr_async.py
  src/sdc11073/provider/subscriptionmgr_base.py
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/roles/audiopauseprovider.py
  src/sdc11073/roles/clockprovider.py
  src/sdc11073/roles/componentprovider.py
  src/sdc11073/roles/contextprovider.py
  src/sdc11073/roles/metricprovider.py
  src/sdc11073/roles/nomenclature.py
  src/sdc11073/roles/operationprovider.py
  src/sdc11073/roles/patientcontextprovider.py
  src/sdc11073/roles/product.py
  src/sdc11073/roles/providerbase.py
  src/sdc11073/xml_types/msg_types.py
  tests/70041_MDIB_Final.xml
  tests/70041_MDIB_multi.xml
  tests/mdib_tns.xml
  tests/mdib_two_mds.xml
  tests/test_client_device.py
  tests/test_operations.py
  tests/test_tutorial.py
  tutorial/consumer/consumer.py
Labels: v2

#270 fix TID252
  src/sdc11073/dispatch/messageconverter.py
  src/sdc11073/dispatch/pathelementregistry.py
  src/sdc11073/httpserver/httprequesthandler.py
  src/sdc11073/httpserver/httpserverimpl.py
  src/sdc11073/provider/periodicreports.py
  src/sdc11073/provider/porttypes/containmenttreeserviceimpl.py
  src/sdc11073/provider/porttypes/getserviceimpl.py
  src/sdc11073/provider/porttypes/localizationservice.py
  src/sdc11073/provider/scopesfactory.py
  src/sdc11073/provider/subscriptionmgr.py
  src/sdc11073/pysoap/msgfactory.py
  src/sdc11073/xml_types/actions.py
  src/sdc11073/xml_types/dpws_types.py
  src/sdc11073/xml_types/eventing_types.py
  src/sdc11073/xml_types/ext_qnames.py
  src/sdc11073/xml_types/mex_types.py
  src/sdc11073/xml_types/msg_qnames.py
  src/sdc11073/xml_types/msg_types.py
  src/sdc11073/xml_types/pm_qnames.py
  src/sdc11073/xml_types/wsd_types.py
Labels: enhancement, v2

#269 Feature/waveform role provider
  CHANGELOG.md
  src/sdc11073/intervaltimer.py
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/providermdib.py
  src/sdc11073/mdib/providermdibxtra.py
  src/sdc11073/mdib/providerwaveform.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/provider/components.py
  src/sdc11073/provider/operations.py
  src/sdc11073/provider/periodicreports.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/provider/waveforms.py
  src/sdc11073/pysoap/msgfactory.py
  src/sdc11073/pysoap/soapclient.py
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/roles/product.py
  src/sdc11073/roles/protocols.py
  src/sdc11073/roles/waveformprovider/__init__.py
  src/sdc11073/roles/waveformprovider/realtimesamples.py
  src/sdc11073/roles/waveformprovider/waveformproviderimpl.py
  src/sdc11073/roles/waveformprovider/waveforms.py
  src/sdc11073/xml_types/eventing_types.py
  src/sdc11073/xml_types/msg_types.py
  src/sdc11073/xml_types/xml_structure.py
  tests/test_client_device.py
  tests/test_device_subscriptions.py
  tests/test_device_waveform.py
  tests/test_operations.py
  tests/test_tutorial.py
Labels: v2

#274 Modify python versions
  .github/workflows/build.yml
  CHANGELOG.md
  codecov.yml
  pyproject.toml
Labels: v1
