Repository Draegerwerk/sdc11073, pull requests merged in 2023-07, with the labels that each got.

#192 fix nsmap bug
  CHANGELOG.md
  src/sdc11073/commlog.py
  src/sdc11073/compression.py
  src/sdc11073/mdib/clientmdib.py
  src/sdc11073/mdib/containerbase.py
  src/sdc11073/mdib/containerproperties.py
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/devicemdib.py
  src/sdc11073/mdib/devicewaveform.py
  src/sdc11073/mdib/mdibbase.py
  src/sdc11073/mdib/msgreader.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/observableproperties/observables.py
  src/sdc11073/pmtypes.py
  src/sdc11073/pysoap/soapclient.py
  src/sdc11073/pysoap/soapenvelope.py
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/sdcclient/hostedservice.py
  src/sdc11073/sdcclient/operations.py
  src/sdc11073/sdcclient/sdcclientimpl.py
  src/sdc11073/sdcdevice/exceptions.py
  src/sdc11073/sdcdevice/httpserver.py
  src/sdc11073/sdcdevice/intervaltimer.py
  src/sdc11073/sdcdevice/sco.py
  src/sdc11073/sdcdevice/sdc_handlers.py
  src/sdc11073/sdcdevice/sdcdeviceimpl.py
  src/sdc11073/sdcdevice/sdcservicesimpl.py
  src/sdc11073/sdcdevice/subscriptionmgr.py
  src/sdc11073/xmlparsing.py
  tests/test_mdib.py
Labels: bug

#195 194 feature add mypy
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/build.yml
  .github/workflows/mypy.yml
  .github/workflows/publish.yml
  .github/workflows/ruff.yml
  CHANGELOG.md
  pyproject.toml
Labels: enhancement

#219 Fix/node text property
  src/sdc11073/xml_types/dataconverters.py
  src/sdc11073/xml_types/msg_types.py
  src/sdc11073/xml_types/pm_types.py
  src/sdc11073/xml_types/xml_structure.py
  tests/test_pmtypes.py
Labels: bug, v2

#220 217 feature split build workflows into smaller ones
  .github/workflows/build.yml
  .github/workflows/mypy.yml
  .github/workflows/ruff.yml
  pyproject.toml
Labels: bug, v2
