Repository Draegerwerk/sdc11073, pull requests merged in 2023-09, with the labels that each got.

#245 Fix/nsmap copy bug
  CHANGELOG.md
  examples/requestmanipulator.py
  pyproject.toml
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/consumer/manipulator.py
  src/sdc11073/consumer/subscription.py
  src/sdc11073/mdib/containerbase.py
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/mdibbase.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/provider/dpwshostedservice.py
  src/sdc11073/provider/porttypes/descriptioneventserviceimpl.py
  src/sdc11073/provider/porttypes/porttypebase.py
  src/sdc11073/provider/subscriptionmgr.py
  src/sdc11073/provider/subscriptionmgr_async.py
  src/sdc11073/provider/subscriptionmgr_base.py
  src/sdc11073/pysoap/msgfactory.py
  src/sdc11073/pysoap/msgreader.py
  src/sdc11073/pysoap/soapenvelope.py
  src/sdc11073/xml_types/addressing_types.py
  src/sdc11073/xml_types/basetypes.py
  src/sdc11073/xml_types/pm_types.py
  src/sdc11073/xml_types/xml_structure.py
  src/sdc11073/xml_utils.py
  tests/test_xml_utils.py
Labels: bug, v2

#248 fix RUF012 #156
  src/sdc11073/definitions_base.py
  src/sdc11073/definitions_sdc.py
  src/sdc11073/httpserver/compression.py
  src/sdc11073/mdib/consumermdibxtra.py
  src/sdc11073/mdib/descriptorcontainers.py
  src/sdc11073/mdib/statecontainers.py
  src/sdc11073/provider/porttypes/porttypebase.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/pysoap/soapenvelope.py
  src/sdc11073/wsdiscovery/wsdimpl.py
  src/sdc11073/xml_types/addressing_types.py
  src/sdc11073/xml_types/basetypes.py
  src/sdc11073/xml_types/dataconverters.py
  src/sdc11073/xml_types/dpws_types.py
  src/sdc11073/xml_types/eventing_types.py
  src/sdc11073/xml_types/mex_types.py
  src/sdc11073/xml_types/msg_types.py
  src/sdc11073/xml_types/wsd_types.py
  src/sdc11073/xml_types/xml_structure.py
  tests/test_mdib.py
Labels: enhancement, v2

#259 expose the http_server_timeout parameter on the SdcDevice interface
  CHANGELOG.md
  src/sdc11073/sdcdevice/sdcdeviceimpl.py
Labels: v1

#260 add version 1.3.0 to the changelog
  CHANGELOG.md
Labels: v1

#265 Fix/use ws addressing 2006
  .github/workflows/build.yml
  CHANGELOG.md
  pyproject.toml
  src/sdc11073/commlog.py
  src/sdc11073/provider/porttypes/contextserviceimpl.py
  src/sdc11073/provider/porttypes/descriptioneventserviceimpl.py
  src/sdc11073/provider/porttypes/setserviceimpl.py
  src/sdc11073/provider/porttypes/stateeventserviceimpl.py
  src/sdc11073/provider/porttypes/waveformserviceimpl.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/provider/subscriptionmgr_base.py
  src/sdc11073/pysoap/msgreader.py
  src/sdc11073/wsdiscovery/networkingthread.py
  src/sdc11073/xml_types/addressing_types.py
  src/sdc11073/xml_utils.py
  src/sdc11073/xsd/addressing.xsd
  tests/mockstuff.py
Labels: bug, v2
