Repository Draegerwerk/sdc11073, pull requests merged in 2024-02, with the labels that each got.

#324 Fix/httpreturncodeerror
  CHANGELOG.md
  pyproject.toml
  src/sdc11073/pysoap/soapclient.py
  src/sdc11073/sdcclient/subscription.py
Labels: bug, v1

#327 fix isConnected bug
  CHANGELOG.md
  src/sdc11073/sdcclient/sdcclientimpl.py
  src/sdc11073/sdcclient/subscription.py
Labels: bug, v1

#338 fix runtime error
  CHANGELOG.md
  src/sdc11073/wsdiscovery/wsdimpl.py
Labels: bug, v2.0

#337 fix runtime error
  CHANGELOG.md
  src/sdc11073/wsdiscovery.py
Labels: bug, v1

#346 fix inconsistent InstanceId in GetMdibResponse
  CHANGELOG.md
  src/sdc11073/mdib/mdibbase.py
  tests/mockstuff.py
  tests/test_client_device.py
Labels: v2

#351 fixed possible exception in ConsumerMdib._get_context_states
  CHANGELOG.md
  src/sdc11073/mdib/consumermdib.py
  tests/test_client_device.py
Labels: v2

#352 Fix/reference tests
  CHANGELOG.md
  examples/ReferenceTest/reference_consumer.py
  examples/ReferenceTest/reference_provider.py
  examples/ReferenceTest/test_reference.py
  tutorial/provider/provider.py
Labels: v2

#319 fixed possible error in alarmprovider #293
  CHANGELOG.md
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/roles/audiopauseprovider.py
  src/sdc11073/roles/clockprovider.py
  tests/mdib_tns.xml
  tests/test_alarmprovider.py
Labels: bug, v1
