Repository Draegerwerk/sdc11073, pull requests merged in 2024-01, with the labels that each got.

#306 fix instance comparison of extensions
  CHANGELOG.md
  src/sdc11073/mdib/containerproperties.py
  tests/test_pmtypes.py
Labels: bug, v1

#310 fix instance comparison of extensions
  CHANGELOG.md
  src/sdc11073/xml_types/xml_structure.py
  tests/test_pmtypes.py
Labels: bug, v2, v2.0

#315 added xml header to wsdiscovery soap messages
  CHANGELOG.md
  src/sdc11073/wsdiscovery.py
Labels: v1

#302 bug: isConnected may be missleading
  CHANGELOG.md
  examples/ReferenceTest/test_reference.py
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/consumer/subscription.py
  tests/test_client_device.py
Labels: bug, v2, v2.0

#301 Feature/split transaction
  CHANGELOG.md
  src/sdc11073/consumer/consumerimpl.py
  src/sdc11073/mdib/providermdib.py
  src/sdc11073/mdib/providermdibxtra.py
  src/sdc11073/mdib/transactions.py
  src/sdc11073/mdib/transactionsprotocol.py
  src/sdc11073/provider/operations.py
  src/sdc11073/provider/providerimpl.py
  src/sdc11073/pysoap/soapclient_async.py
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/roles/audiopauseprovider.py
  src/sdc11073/roles/clockprovider.py
  src/sdc11073/roles/componentprovider.py
  src/sdc11073/roles/contextprovider.py
  src/sdc11073/roles/metricprovider.py
  src/sdc11073/roles/product.py
  src/sdc11073/roles/protocols.py
  src/sdc11073/roles/providerbase.py
  src/sdc11073/roles/waveformprovider/waveformproviderimpl.py
  tests/test_alertsignaldelegate.py
  tests/test_client_device.py
  tests/test_device_services.py
  tests/test_device_subscriptions.py
  tests/test_mdib.py
  tests/test_operations.py
  tests/test_string_enum_descriptors.py
  tests/test_transaction.py
  tests/test_tutorial.py
Labels: v2, v2.0

#317 fixed wrong typing in LocalizedText constructor
  CHANGELOG.md
  src/sdc11073/xml_types/pm_types.py
Labels: bug, v2, v2.0

#321 fixed possible caching errors in AlarmProvider and AudioPauseProvider
  CHANGELOG.md
  src/sdc11073/roles/alarmprovider.py
  src/sdc11073/roles/audiopauseprovider.py
  tests/test_operations.py
Labels: bug, v2
